STEPBible/step

step-core/src/main/resources/InteractiveBundle.properties
=> Changed text from "Apocrypha" to "Deuterocanon"

step-web/src/main/webapp/scss/cross_references.scss, step-web/src/main/webapp/scss/defaults.scss, step-web/src/main/webapp/scss/passage.scss, step-web/src/main/webapp/scss/passage_columns.scss, step-web/src/main/webapp/scss/passage_display.scss, step-web/src/main/webapp/scss/search_display.scss
- Increased font size of search results
- Moved padding/scroll from passageContenHolder to first child of passageContent
=> TYNSTEP-1403 Fixed some css styles which affect spacing

step-web/src/main/webapp/scss/sidebar_definition.scss
=> TYNSTEP-1405 Ensure padding in panels in the right sidebar

.gitignore, step-web/src/main/webapp/js/backbone/views/view_main_search.js, step-web/src/main/webapp/js/step.util.js
I added down arrows to main search command line.
=> Added down arrows to version and bible reference items in main search bar

step-web/src/main/webapp/scss/passage_options.scss
=> Styled arrows to show at the bottom of the panel

step-web/src/main/webapp/js/backbone/views/view_main_search.js
aka avoid having to type Enter or click the magnifying glass
=> Submit search when data is updated

step-web/src/main/webapp/jsps/menu.jsp
=> Added feedback icon back to header

step-web/src/main/webapp/js/backbone/views/view_display_passage.js, step-web/src/main/webapp/js/step.util.js, step-web/src/main/webapp/scss/cross_references.scss, step-web/src/main/webapp/scss/passage.scss, step-web/src/main/webapp/scss/passage_display.scss
(avoids issue with width not being properly based on the size of the content)
- Converted crossref hover to qtip (more stable with hover on/off)
=> Set up verseNumber qtip to fetch data before creating qtip

pom.xml, step-core/pom.xml, step-core/src/main/java/com/tyndalehouse/step/core/data/EntityDoc.java, step-core/src/main/java/com/tyndalehouse/step/core/models/BookName.java, step-core/src/main/java/com/tyndalehouse/step/core/models/KeyWrapper.java, step-core/src/main/java/com/tyndalehouse/step/core/models/LookupOption.java, step-core/src/main/java/com/tyndalehouse/step/core/models/OsisWrapper.java, step-core/src/main/java/com/tyndalehouse/step/core/service/impl/VocabularyServiceImpl.java, step-web/pom.xml, step-web/src/main/java/com/tyndalehouse/step/guice/StepWebModule.java, step-web/src/main/java/com/tyndalehouse/step/rest/controllers/InternationalJsonController.java, step-web/src/main/java/com/tyndalehouse/step/rest/controllers/SearchPageController.java, step-web/src/main/java/com/tyndalehouse/step/rest/framework/AbstractAjaxController.java, step-web/src/main/java/com/tyndalehouse/step/rest/framework/FrontController.java, step-web/src/main/java/com/tyndalehouse/step/rest/framework/JsonResourceBundle.java, step-web/src/main/java/com/tyndalehouse/step/rest/framework/ObjectMapperProvider.java, step-web/src/test/java/com/tyndalehouse/step/rest/framework/FrontControllerTest.java
Update due to security vulnerabilities in the old library.
=> update the jackson-asl library to current version

step-web/src/main/webapp/scss/fonts.scss
Increase Arabic font size, and remove it from the td element override.
=> Increase Arabic font size

step-core/src/main/resources/com/tyndalehouse/step/core/service/jsword/impl/default.xsl, step-core/src/main/resources/com/tyndalehouse/step/core/service/jsword/impl/interlinear.xsl, step-web/pom.xml, step-web/src/main/webapp/js/backbone/views/view_display_passage.js, step-web/src/main/webapp/js/backbone/views/view_quick_lexicon.js, step-web/src/main/webapp/js/backbone/views/view_sidebar.js, step-web/src/main/webapp/js/step.util.js
=> Show variants

step-core/src/main/resources/com/tyndalehouse/step/core/service/jsword/impl/default.xsl
Remove extra space between colon and verse number
=> Correct display for hbo language

step-web/src/main/webapp/js/backbone/views/view_examples.js
=> Revert "Codex nathan"

step-web/src/main/webapp/js/step_ready.js
=> Revert "Ensure landing passage appears in recent bookmarks (#7)"

step-web/src/main/webapp/js/step_ready.js
=> Revert "Add landing passage to recent bookmarks (#14)"

step-web/src/main/webapp/html/J_AppsHtml/J_Genealogy/j_genealogy.html
=> Revert "Fix genealogy hamburger menu alignment (#23)"

step-web/src/main/webapp/css/J_AppsCss/J_Framework/j_framework.dropdownMenu.css, step-web/src/main/webapp/html/J_AppsHtml/J_Genealogy/j_genealogy.html
=> Revert "Adjust genealogy menu spacing and help icon (#25)"

step-web/src/main/webapp/js/J_AppsJs/J_Genealogy/j_genealogy.js
=> Revert "Hide genealogy share link on mobile (#30)"

step-web/src/main/webapp/js/J_AppsJs/J_Genealogy/j_genealogy.js
=> Revert "Make genealogy timeline bar white (#36)"

step-web/src/main/webapp/css/J_AppsCss/J_Framework/j_framework.tableWithSearchBox.css
=> Revert "Make genealogy search placeholder text light gray (#39)"

step-web/src/main/webapp/js/J_AppsJs/J_Genealogy/j_genealogy.js
=> Revert "Hide genealogy share link on mobile devices (#32)"

step-web/src/main/webapp/html/J_AppsHtml/J_Genealogy/j_genealogy.html
=> Revert "Use Bootstrap buttons in genealogy context menu (#47)"
